### PR TITLE
docs: add AUR instructions

### PR DESCRIPTION
**Pull request by malteo**
I reorganized the `Install` section and split the launch command in a new `Usage` one, let me know if that's correct for you

### CODE REVIEW

**Comment by Lifailon** [comment]
Very interesting implementation!
I've never used the 'Arch' distribution, so I'm curious. Tell me, were you able to check the installation from `aur` and the functionality of the application on the system?
Can you also tell me whether packages need to be uploaded manually with each version or is there synchronization with git?

**Comment by malteo** [comment]
To be clear, I also wrote the `PKGBUILD` and published it in the AUR (you can inspect it [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lazyjournal)).

It follows Arch's [Go package guidelines](https://wiki.archlinux.org/title/Go_package_guidelines) and is built in a [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:How_to_be_a_packager#Change_and_build).

I indeed installed and tested the basic functionality of the app built from my package, and found it working fine.

There's no need for you to upload anything else, I'll star the repo and follow the releases to update the package accordingly.

**Comment by Lifailon** [comment]
Great, thanks for the feedback and support!

**Comment by Lifailon** [comment]
> There's no need for you to upload anything else, I'll star the repo and follow the releases to update the package accordingly.

also mentioned you in the README file for your contributions ;)

**Pull request merged**
